
package uk.ac.horizon.ug.exploding.client.model;
/** 
 * Identity element is ID.
 * 
 * Autogenerated by bean2java.xsl */
public class Member //implements uk.ac.horizon.ug.exploding.db.StatsModifier
{

  /** no-arg cons */
  public Member()
  {
  }

  /* implements ., i.e. 
    uk.ac.horizon.ug.exploding.db.Member */
  
  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _ID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getID()
  {
  
    return _ID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setID(java.lang.String ID)
  {
  
    this._ID = ID;
    
  }

  /** is set?
   */
  public boolean isSetID() {
    return this._ID != null; 
  }

  /** unset
   */
  public void unsetID()  {
    this._ID = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _playerID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getPlayerID()
  {
  
    return _playerID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setPlayerID(java.lang.String playerID)
  {
  
    this._playerID = playerID;
    
  }

  /** is set?
   */
  public boolean isSetPlayerID() {
    return this._playerID != null; 
  }

  /** unset
   */
  public void unsetPlayerID()  {
    this._playerID = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _gameID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getGameID()
  {
  
    return _gameID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setGameID(java.lang.String gameID)
  {
  
    this._gameID = gameID;
    
  }

  /** is set?
   */
  public boolean isSetGameID() {
    return this._gameID != null; 
  }

  /** unset
   */
  public void unsetGameID()  {
    this._gameID = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _parentMemberID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getParentMemberID()
  {
  
    return _parentMemberID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setParentMemberID(java.lang.String parentMemberID)
  {
  
    this._parentMemberID = parentMemberID;
    
  }

  /** is set?
   */
  public boolean isSetParentMemberID() {
    return this._parentMemberID != null; 
  }

  /** unset
   */
  public void unsetParentMemberID()  {
    this._parentMemberID = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _zone;
  
  /** getter - 
   */
  public java.lang.Integer getZone()
  {
  
    return _zone;
    
  }

  /** setter - 
   */
  public void setZone(java.lang.Integer zone)
  {
  
    this._zone = zone;
    
  }

  /** is set?
   */
  public boolean isSetZone() {
    return this._zone != null; 
  }

  /** unset
   */
  public void unsetZone()  {
    this._zone = null; 
  }

  /** internal value - 
   */
  protected Position _position;
  
  /** getter - 
   */
  public Position getPosition()
  {
  
    return _position;
    
  }

  /** setter - 
   */
  public void setPosition(Position position)
  {
  
    this._position = position;
    
  }

  /** is set?
   */
  public boolean isSetPosition() {
    return this._position != null; 
  }

  /** unset
   */
  public void unsetPosition()  {
    this._position = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _health;
  
  /** getter - 
   */
  public java.lang.Integer getHealth()
  {
  
    return _health;
    
  }

  /** setter - 
   */
  public void setHealth(java.lang.Integer health)
  {
  
    this._health = health;
    
  }

  /** is set?
   */
  public boolean isSetHealth() {
    return this._health != null; 
  }

  /** unset
   */
  public void unsetHealth()  {
    this._health = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _wealth;
  
  /** getter - 
   */
  public java.lang.Integer getWealth()
  {
  
    return _wealth;
    
  }

  /** setter - 
   */
  public void setWealth(java.lang.Integer wealth)
  {
  
    this._wealth = wealth;
    
  }

  /** is set?
   */
  public boolean isSetWealth() {
    return this._wealth != null; 
  }

  /** unset
   */
  public void unsetWealth()  {
    this._wealth = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _brains;
  
  /** getter - 
   */
  public java.lang.Integer getBrains()
  {
  
    return _brains;
    
  }

  /** setter - 
   */
  public void setBrains(java.lang.Integer brains)
  {
  
    this._brains = brains;
    
  }

  /** is set?
   */
  public boolean isSetBrains() {
    return this._brains != null; 
  }

  /** unset
   */
  public void unsetBrains()  {
    this._brains = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _action;
  
  /** getter - 
   */
  public java.lang.Integer getAction()
  {
  
    return _action;
    
  }

  /** setter - 
   */
  public void setAction(java.lang.Integer action)
  {
  
    this._action = action;
    
  }

  /** is set?
   */
  public boolean isSetAction() {
    return this._action != null; 
  }

  /** unset
   */
  public void unsetAction()  {
    this._action = null; 
  }

  /** internal value - 
   */
  protected java.lang.Boolean _carried;
  
  /** getter - 
   */
  public java.lang.Boolean getCarried()
  {
  
    return _carried;
    
  }

  /** setter - 
   */
  public void setCarried(java.lang.Boolean carried)
  {
  
    this._carried = carried;
    
  }

  /** is set?
   */
  public boolean isSetCarried() {
    return this._carried != null; 
  }

  /** unset
   */
  public void unsetCarried()  {
    this._carried = null; 
  }

  /* implements uk.ac.horizon.ug.exploding.db.StatsModifier.xml, i.e. 
    uk.ac.horizon.ug.exploding.db.StatsModifier */
  
    /* property health defined in . */
      
  /** internal value - 
   */
  protected java.lang.Integer _healthMax;
  
  /** getter - 
   */
  public java.lang.Integer getHealthMax()
  {
  
    return _healthMax;
    
  }

  /** setter - 
   */
  public void setHealthMax(java.lang.Integer healthMax)
  {
  
    this._healthMax = healthMax;
    
  }

  /** is set?
   */
  public boolean isSetHealthMax() {
    return this._healthMax != null; 
  }

  /** unset
   */
  public void unsetHealthMax()  {
    this._healthMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _healthMin;
  
  /** getter - 
   */
  public java.lang.Integer getHealthMin()
  {
  
    return _healthMin;
    
  }

  /** setter - 
   */
  public void setHealthMin(java.lang.Integer healthMin)
  {
  
    this._healthMin = healthMin;
    
  }

  /** is set?
   */
  public boolean isSetHealthMin() {
    return this._healthMin != null; 
  }

  /** unset
   */
  public void unsetHealthMin()  {
    this._healthMin = null; 
  }

    /* property wealth defined in . */
      
  /** internal value - 
   */
  protected java.lang.Integer _wealthMax;
  
  /** getter - 
   */
  public java.lang.Integer getWealthMax()
  {
  
    return _wealthMax;
    
  }

  /** setter - 
   */
  public void setWealthMax(java.lang.Integer wealthMax)
  {
  
    this._wealthMax = wealthMax;
    
  }

  /** is set?
   */
  public boolean isSetWealthMax() {
    return this._wealthMax != null; 
  }

  /** unset
   */
  public void unsetWealthMax()  {
    this._wealthMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _wealthMin;
  
  /** getter - 
   */
  public java.lang.Integer getWealthMin()
  {
  
    return _wealthMin;
    
  }

  /** setter - 
   */
  public void setWealthMin(java.lang.Integer wealthMin)
  {
  
    this._wealthMin = wealthMin;
    
  }

  /** is set?
   */
  public boolean isSetWealthMin() {
    return this._wealthMin != null; 
  }

  /** unset
   */
  public void unsetWealthMin()  {
    this._wealthMin = null; 
  }

    /* property brains defined in . */
      
  /** internal value - 
   */
  protected java.lang.Integer _brainsMax;
  
  /** getter - 
   */
  public java.lang.Integer getBrainsMax()
  {
  
    return _brainsMax;
    
  }

  /** setter - 
   */
  public void setBrainsMax(java.lang.Integer brainsMax)
  {
  
    this._brainsMax = brainsMax;
    
  }

  /** is set?
   */
  public boolean isSetBrainsMax() {
    return this._brainsMax != null; 
  }

  /** unset
   */
  public void unsetBrainsMax()  {
    this._brainsMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _brainsMin;
  
  /** getter - 
   */
  public java.lang.Integer getBrainsMin()
  {
  
    return _brainsMin;
    
  }

  /** setter - 
   */
  public void setBrainsMin(java.lang.Integer brainsMin)
  {
  
    this._brainsMin = brainsMin;
    
  }

  /** is set?
   */
  public boolean isSetBrainsMin() {
    return this._brainsMin != null; 
  }

  /** unset
   */
  public void unsetBrainsMin()  {
    this._brainsMin = null; 
  }

    /* property action defined in . */
      
  /** internal value - 
   */
  protected java.lang.Integer _actionMax;
  
  /** getter - 
   */
  public java.lang.Integer getActionMax()
  {
  
    return _actionMax;
    
  }

  /** setter - 
   */
  public void setActionMax(java.lang.Integer actionMax)
  {
  
    this._actionMax = actionMax;
    
  }

  /** is set?
   */
  public boolean isSetActionMax() {
    return this._actionMax != null; 
  }

  /** unset
   */
  public void unsetActionMax()  {
    this._actionMax = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _actionMin;
  
  /** getter - 
   */
  public java.lang.Integer getActionMin()
  {
  
    return _actionMin;
    
  }

  /** setter - 
   */
  public void setActionMin(java.lang.Integer actionMin)
  {
  
    this._actionMin = actionMin;
    
  }

  /** is set?
   */
  public boolean isSetActionMin() {
    return this._actionMin != null; 
  }

  /** unset
   */
  public void unsetActionMin()  {
    this._actionMin = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _instant;
  
  /** getter - 
   */
  public java.lang.Integer getInstant()
  {
  
    return _instant;
    
  }

  /** setter - 
   */
  public void setInstant(java.lang.Integer instant)
  {
  
    this._instant = instant;
    
  }

  /** is set?
   */
  public boolean isSetInstant() {
    return this._instant != null; 
  }

  /** unset
   */
  public void unsetInstant()  {
    this._instant = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _flags;
  
  /** getter - 
   */
  public java.lang.Integer getFlags()
  {
  
    return _flags;
    
  }

  /** setter - 
   */
  public void setFlags(java.lang.Integer flags)
  {
  
    this._flags = flags;
    
  }

  /** is set?
   */
  public boolean isSetFlags() {
    return this._flags != null; 
  }

  /** unset
   */
  public void unsetFlags()  {
    this._flags = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _absolute;
  
  /** getter - 
   */
  public java.lang.Integer getAbsolute()
  {
  
    return _absolute;
    
  }

  /** setter - 
   */
  public void setAbsolute(java.lang.Integer absolute)
  {
  
    this._absolute = absolute;
    
  }

  /** is set?
   */
  public boolean isSetAbsolute() {
    return this._absolute != null; 
  }

  /** unset
   */
  public void unsetAbsolute()  {
    this._absolute = null; 
  }

  /** equals */
  public boolean equals(Object o) {
    if (o==null) return false;
    if (!(o instanceof Member)) return false;
    Member oo = (Member)o;
      if (_ID!=oo._ID &&
        (_ID==null || oo._ID==null ||
         !_ID.equals(oo._ID)))
      return false;
    if (_playerID!=oo._playerID &&
        (_playerID==null || oo._playerID==null ||
         !_playerID.equals(oo._playerID)))
      return false;
    if (_gameID!=oo._gameID &&
        (_gameID==null || oo._gameID==null ||
         !_gameID.equals(oo._gameID)))
      return false;
    if (_parentMemberID!=oo._parentMemberID &&
        (_parentMemberID==null || oo._parentMemberID==null ||
         !_parentMemberID.equals(oo._parentMemberID)))
      return false;
    if (_zone!=oo._zone &&
        (_zone==null || oo._zone==null ||
         !_zone.equals(oo._zone)))
      return false;
    if (_position!=oo._position &&
        (_position==null || oo._position==null ||
         !_position.equals(oo._position)))
      return false;
    if (_health!=oo._health &&
        (_health==null || oo._health==null ||
         !_health.equals(oo._health)))
      return false;
    if (_wealth!=oo._wealth &&
        (_wealth==null || oo._wealth==null ||
         !_wealth.equals(oo._wealth)))
      return false;
    if (_brains!=oo._brains &&
        (_brains==null || oo._brains==null ||
         !_brains.equals(oo._brains)))
      return false;
    if (_action!=oo._action &&
        (_action==null || oo._action==null ||
         !_action.equals(oo._action)))
      return false;
    if (_carried!=oo._carried &&
        (_carried==null || oo._carried==null ||
         !_carried.equals(oo._carried)))
      return false;

    /* property health defined in . */
          if (_healthMax!=oo._healthMax &&
        (_healthMax==null || oo._healthMax==null ||
         !_healthMax.equals(oo._healthMax)))
      return false;
    if (_healthMin!=oo._healthMin &&
        (_healthMin==null || oo._healthMin==null ||
         !_healthMin.equals(oo._healthMin)))
      return false;

    /* property wealth defined in . */
          if (_wealthMax!=oo._wealthMax &&
        (_wealthMax==null || oo._wealthMax==null ||
         !_wealthMax.equals(oo._wealthMax)))
      return false;
    if (_wealthMin!=oo._wealthMin &&
        (_wealthMin==null || oo._wealthMin==null ||
         !_wealthMin.equals(oo._wealthMin)))
      return false;

    /* property brains defined in . */
          if (_brainsMax!=oo._brainsMax &&
        (_brainsMax==null || oo._brainsMax==null ||
         !_brainsMax.equals(oo._brainsMax)))
      return false;
    if (_brainsMin!=oo._brainsMin &&
        (_brainsMin==null || oo._brainsMin==null ||
         !_brainsMin.equals(oo._brainsMin)))
      return false;

    /* property action defined in . */
          if (_actionMax!=oo._actionMax &&
        (_actionMax==null || oo._actionMax==null ||
         !_actionMax.equals(oo._actionMax)))
      return false;
    if (_actionMin!=oo._actionMin &&
        (_actionMin==null || oo._actionMin==null ||
         !_actionMin.equals(oo._actionMin)))
      return false;
    if (_instant!=oo._instant &&
        (_instant==null || oo._instant==null ||
         !_instant.equals(oo._instant)))
      return false;
    if (_flags!=oo._flags &&
        (_flags==null || oo._flags==null ||
         !_flags.equals(oo._flags)))
      return false;
    if (_absolute!=oo._absolute &&
        (_absolute==null || oo._absolute==null ||
         !_absolute.equals(oo._absolute)))
      return false;

    return true;
  }
  /** hashcode */
  public int hashCode() {
    int val = 0;
      if (_ID!=null) val = val ^ _ID.hashCode();
    if (_playerID!=null) val = val ^ _playerID.hashCode();
    if (_gameID!=null) val = val ^ _gameID.hashCode();
    if (_parentMemberID!=null) val = val ^ _parentMemberID.hashCode();
    if (_zone!=null) val = val ^ _zone.hashCode();
    if (_position!=null) val = val ^ _position.hashCode();
    if (_health!=null) val = val ^ _health.hashCode();
    if (_wealth!=null) val = val ^ _wealth.hashCode();
    if (_brains!=null) val = val ^ _brains.hashCode();
    if (_action!=null) val = val ^ _action.hashCode();
    if (_carried!=null) val = val ^ _carried.hashCode();

    /* property health defined in . */
          if (_healthMax!=null) val = val ^ _healthMax.hashCode();
    if (_healthMin!=null) val = val ^ _healthMin.hashCode();

    /* property wealth defined in . */
          if (_wealthMax!=null) val = val ^ _wealthMax.hashCode();
    if (_wealthMin!=null) val = val ^ _wealthMin.hashCode();

    /* property brains defined in . */
          if (_brainsMax!=null) val = val ^ _brainsMax.hashCode();
    if (_brainsMin!=null) val = val ^ _brainsMin.hashCode();

    /* property action defined in . */
          if (_actionMax!=null) val = val ^ _actionMax.hashCode();
    if (_actionMin!=null) val = val ^ _actionMin.hashCode();
    if (_instant!=null) val = val ^ _instant.hashCode();
    if (_flags!=null) val = val ^ _flags.hashCode();
    if (_absolute!=null) val = val ^ _absolute.hashCode();

    return val;
  }
  /** tostring */
  public String toString() {
    StringBuilder str = new StringBuilder("Member:");
    
    str.append("{");
    
    
	str.append("ID=");
	if (_ID!=null) {
	    str.append(_ID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("playerID=");
	if (_playerID!=null) {
	    str.append(_playerID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("gameID=");
	if (_gameID!=null) {
	    str.append(_gameID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("parentMemberID=");
	if (_parentMemberID!=null) {
	    str.append(_parentMemberID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("zone=");
	if (_zone!=null) {
	    str.append(_zone.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("position=");
	if (_position!=null) {
	    str.append(_position.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("health=");
	if (_health!=null) {
	    str.append(_health.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("wealth=");
	if (_wealth!=null) {
	    str.append(_wealth.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("brains=");
	if (_brains!=null) {
	    str.append(_brains.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("action=");
	if (_action!=null) {
	    str.append(_action.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("carried=");
	if (_carried!=null) {
	    str.append(_carried.toString());
	} else {
	    str.append("null");
	}
    
    str.append("}");

    return str.toString();
  }

}
