
package uk.ac.horizon.ug.exploding.client.model;
/** 
 * Identity element is ID.
 * 
 * Autogenerated by bean2java.xsl */
public class Zone
{

  /** no-arg cons */
  public Zone()
  {
  }

  /* implements ., i.e. 
    uk.ac.horizon.ug.exploding.db.Zone */
  
  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _ID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getID()
  {
  
    return _ID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setID(java.lang.String ID)
  {
  
    this._ID = ID;
    
  }

  /** is set?
   */
  public boolean isSetID() {
    return this._ID != null; 
  }

  /** unset
   */
  public void unsetID()  {
    this._ID = null; 
  }

  /** internal value - 
   * max length = 20.
  
   */
  protected java.lang.String _contentGroupID;
  
  /** getter - 
   * max length = 20.
  
   */
  public java.lang.String getContentGroupID()
  {
  
    return _contentGroupID;
    
  }

  /** setter - 
   * max length = 20.
  
   */
  public void setContentGroupID(java.lang.String contentGroupID)
  {
  
    this._contentGroupID = contentGroupID;
    
  }

  /** is set?
   */
  public boolean isSetContentGroupID() {
    return this._contentGroupID != null; 
  }

  /** unset
   */
  public void unsetContentGroupID()  {
    this._contentGroupID = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _orgId;
  
  /** getter - 
   */
  public java.lang.Integer getOrgId()
  {
  
    return _orgId;
    
  }

  /** setter - 
   */
  public void setOrgId(java.lang.Integer orgId)
  {
  
    this._orgId = orgId;
    
  }

  /** is set?
   */
  public boolean isSetOrgId() {
    return this._orgId != null; 
  }

  /** unset
   */
  public void unsetOrgId()  {
    this._orgId = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _name;
  
  /** getter - 
   */
  public java.lang.String getName()
  {
  
    return _name;
    
  }

  /** setter - 
   */
  public void setName(java.lang.String name)
  {
  
    this._name = name;
    
  }

  /** is set?
   */
  public boolean isSetName() {
    return this._name != null; 
  }

  /** unset
   */
  public void unsetName()  {
    this._name = null; 
  }

  /** internal value - 
   */
  protected java.lang.String _ref;
  
  /** getter - 
   */
  public java.lang.String getRef()
  {
  
    return _ref;
    
  }

  /** setter - 
   */
  public void setRef(java.lang.String ref)
  {
  
    this._ref = ref;
    
  }

  /** is set?
   */
  public boolean isSetRef() {
    return this._ref != null; 
  }

  /** unset
   */
  public void unsetRef()  {
    this._ref = null; 
  }

  /** internal value - 
   */
  protected java.lang.Integer _polygon;
  
  /** getter - 
   */
  public java.lang.Integer getPolygon()
  {
  
    return _polygon;
    
  }

  /** setter - 
   */
  public void setPolygon(java.lang.Integer polygon)
  {
  
    this._polygon = polygon;
    
  }

  /** is set?
   */
  public boolean isSetPolygon() {
    return this._polygon != null; 
  }

  /** unset
   */
  public void unsetPolygon()  {
    this._polygon = null; 
  }

  /** internal value - 
   */
  protected java.lang.Double _radius;
  
  /** getter - 
   */
  public java.lang.Double getRadius()
  {
  
    return _radius;
    
  }

  /** setter - 
   */
  public void setRadius(java.lang.Double radius)
  {
  
    this._radius = radius;
    
  }

  /** is set?
   */
  public boolean isSetRadius() {
    return this._radius != null; 
  }

  /** unset
   */
  public void unsetRadius()  {
    this._radius = null; 
  }

  /** internal value - 
   */
  protected Position[] _coordinates;
  
  /** getter - 
   */
  public Position[] getCoordinates()
  {
  
    return _coordinates;
    
  }

  /** setter - 
   */
  public void setCoordinates(Position[] coordinates)
  {
  
    this._coordinates = coordinates;
    
  }

  /** is set?
   */
  public boolean isSetCoordinates() {
    return this._coordinates != null; 
  }

  /** unset
   */
  public void unsetCoordinates()  {
    this._coordinates = null; 
  }

  /** equals */
  public boolean equals(Object o) {
    if (o==null) return false;
    if (!(o instanceof Zone)) return false;
    Zone oo = (Zone)o;
      if (_ID!=oo._ID &&
        (_ID==null || oo._ID==null ||
         !_ID.equals(oo._ID)))
      return false;
    if (_contentGroupID!=oo._contentGroupID &&
        (_contentGroupID==null || oo._contentGroupID==null ||
         !_contentGroupID.equals(oo._contentGroupID)))
      return false;
    if (_orgId!=oo._orgId &&
        (_orgId==null || oo._orgId==null ||
         !_orgId.equals(oo._orgId)))
      return false;
    if (_name!=oo._name &&
        (_name==null || oo._name==null ||
         !_name.equals(oo._name)))
      return false;
    if (_ref!=oo._ref &&
        (_ref==null || oo._ref==null ||
         !_ref.equals(oo._ref)))
      return false;
    if (_polygon!=oo._polygon &&
        (_polygon==null || oo._polygon==null ||
         !_polygon.equals(oo._polygon)))
      return false;
    if (_radius!=oo._radius &&
        (_radius==null || oo._radius==null ||
         !_radius.equals(oo._radius)))
      return false;
    if (_coordinates!=oo._coordinates) {
      if (_coordinates==null || oo._coordinates==null) return false;
      if (_coordinates.length!=oo._coordinates.length) return false;
      for (int i0=0; i0<_coordinates.length; i0++) {
        if (_coordinates[i0]!=oo._coordinates[i0] &&
            (_coordinates[i0]==null || oo._coordinates[i0]==null ||
             !_coordinates[i0].equals(oo._coordinates[i0])))
          return false;
      }
    }

    return true;
  }
  /** hashcode */
  public int hashCode() {
    int val = 0;
      if (_ID!=null) val = val ^ _ID.hashCode();
    if (_contentGroupID!=null) val = val ^ _contentGroupID.hashCode();
    if (_orgId!=null) val = val ^ _orgId.hashCode();
    if (_name!=null) val = val ^ _name.hashCode();
    if (_ref!=null) val = val ^ _ref.hashCode();
    if (_polygon!=null) val = val ^ _polygon.hashCode();
    if (_radius!=null) val = val ^ _radius.hashCode();
    if (_coordinates!=null) {
      // only do hash code on first 20 elements (consider a large binary array)
      for (int i0=0; i0<_coordinates.length && i0<20; i0++) {
        if (_coordinates[i0]!=null) val = val ^ _coordinates[i0].hashCode();
      }
    }

    return val;
  }
  /** tostring */
  public String toString() {
    StringBuilder str = new StringBuilder("Zone:");
    
    str.append("{");
    
    
	str.append("ID=");
	if (_ID!=null) {
	    str.append(_ID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("contentGroupID=");
	if (_contentGroupID!=null) {
	    str.append(_contentGroupID.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("orgId=");
	if (_orgId!=null) {
	    str.append(_orgId.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("name=");
	if (_name!=null) {
	    str.append(_name.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("ref=");
	if (_ref!=null) {
	    str.append(_ref.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("polygon=");
	if (_polygon!=null) {
	    str.append(_polygon.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("radius=");
	if (_radius!=null) {
	    str.append(_radius.toString());
	} else {
	    str.append("null");
	}
    str.append(",");
	str.append("coordinates=");
	if (_coordinates!=null) {
	    str.append(_coordinates.toString());
	} else {
	    str.append("null");
	}
    
    str.append("}");

    return str.toString();
  }

}
